# Name your project!
name: 'dbt_bilbo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_bilbo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_bilbo:
    +materialized: table

vars:
  list_temporelle : ["annee"]
  list_spatiale : ["id_spatial", "upper_libelle", "level", "dimension_spatiale", "type_spatial"]
  list_mesure : []
  list_technique : ["hex_id", "id_split", "geometry", "id_indicateur", "id_fait", "id", "metadata_id", "nic", "objectid", "values"]
  
  
  
  
  
  
  
  
  
  
  
  
  
  list_tech : ["geometry", "id", "zone_id", "id_split", "id_indicateur", "id_fait", "id_thematique", "zb_id", "index_right", "globalid", "grid_code", "unesco_id", "values", "ratio", "ratio_id_spatial", "superficie_ha", "distance", "perimetre", "premiere_detection", "derniere_detection", "date_acq", "date_ortho", "created"]